### PR TITLE
Adding workshape.uk

### PR DESCRIPTION
**Pull request by craigwatson**

### CODE REVIEW

**Comment by nelsonic** [comment]
@craigwatson did workshape send you a "spammy" email...?

**Comment by craigwatson** [comment]
>Craig!
>
>It's Hung, CEO of Workshape
>
>I hope you don't mind my reaching out to you directly, but we're trying to build the best hiring platform for tech in the world and we now need your help.
>
>We've already built this much (check out our site here) but as we come out of public beta, we want to make sure that our product tracks close to the needs of the community we aim to serve. 
>
>Can I ask you to spare 2 minutes to complete our survey What are the most important factors to you when looking for a job as a developer?
>
>Our build priorities are going to be set by the answers you give. We'll release the results to everyone who has completed the survey, most likely published on our blog.  
>
>Thanks so much for taking the time to read this. Thank you for your help - I really appreciate it!
>
>Yours, 
>
>Hung

**Comment by nelsonic** [comment]
Workshape are *trying* to build a way to help developers *avoid* spammy recruiters, i.e: they want to *solve* the problem.
Sure, the CEO sent you this (*unsolicited*) email, but the *intent* is to get your feedback to help people *like* you find work not to send you jobs that are *irrelevant* to you.
Seems a bit harsh to put them on a "spam" blacklist just for reaching out to you. :crying_cat_face:

**Comment by craigwatson** [comment]
Fair point - I guess I have a fairly restrictive definition of spam!

**Comment by nelsonic** [comment]
Yeah, my tolerance to *unsolicited* email is fairly low too. :wink:

**Pull request closed without merging**
