### PR TITLE
Added wegeekit.io

### PR DESCRIPTION
**Pull request by miquelbeltran**

### CODE REVIEW

**Comment by drcongo** [comment]
Any details on this one? Can't find any reference to this domain online.

**Comment by miquelbeltran** [comment]
The website seems down, the LinkedIn is https://www.linkedin.com/company-beta/18021878/ I just got a generic email from them with my email on bcc.
screen shot 2017-05-15 at 15 04 37

**Comment by miquelbeltran** [comment]
BTW, Gmail does not accept the pattern anymore as filter, it complains that the filter is too long :( I wonder which alternatives we have.

**Comment by drcongo** [comment]
That definitely looks like spam to me. On the filter point, yeah, it's been too long for a while now. I currently have it split into 3 separate filters. Bit of a pain but it works. I'd love to find a way of keeping those filters synced with the list.

**Pull request merged**
